<?php

namespace Database\Seeders;

use App\Models\Facility;
use App\Models\FacilityMeter;
use App\Models\SubmeterEquipment;
use Illuminate\Database\Seeder;

class FacilityEquipmentLoadSeeder extends Seeder
{
    public function run(): void
    {
        $facilities = Facility::all();

        foreach ($facilities as $facility) {
            // Remove existing placeholder equipment so fresh realistic loads are populated
            SubmeterEquipment::where('facility_id', $facility->id)->delete();

            $mainMeter = FacilityMeter::where('facility_id', $facility->id)
                ->where('meter_type', 'main')
                ->first();

            $mainMeterId = $mainMeter ? $mainMeter->id : null;
            $facilityName = strtolower($facility->name);

            if (str_contains($facilityName, 'amoranto')) {
                // Amoranto Sports Complex (~45,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Stadium High-Mast LED Floodlight Towers',
                        'category' => 'Lighting',
                        'location' => 'Main Stadium Field & Track',
                        'quantity' => 32,
                        'rated_watts' => 1500,
                        'hours_per_day' => 6,
                        'days_per_month' => 26,
                        'notes' => 'High-intensity athletic field illumination for evening games & training',
                    ],
                    [
                        'name' => 'Olympic Pool Heavy-Duty Circulation & Filtration Pumps',
                        'category' => 'Pumps & Motors',
                        'location' => 'Aquatics Center Pump Room',
                        'quantity' => 4,
                        'rated_watts' => 5500,
                        'hours_per_day' => 18,
                        'days_per_month' => 30,
                        'notes' => 'Continuous filtration and turnover for Olympic-standard competition pool',
                    ],
                    [
                        'name' => 'Indoor Arena Central VRF Air Conditioning Units',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Indoor Gymnasium & Multi-purpose Arena',
                        'quantity' => 4,
                        'rated_watts' => 11000,
                        'hours_per_day' => 10,
                        'days_per_month' => 26,
                        'notes' => 'High-capacity VRF cooling for spectators and players',
                    ],
                    [
                        'name' => 'Concourse & Grandstand High-Bay LED Fixtures',
                        'category' => 'Lighting',
                        'location' => 'Grandstand Concourse & Walkways',
                        'quantity' => 65,
                        'rated_watts' => 120,
                        'hours_per_day' => 12,
                        'days_per_month' => 30,
                        'notes' => 'Public pedestrian and safety lighting',
                    ],
                    [
                        'name' => 'Electronic LED Stadium Video Scoreboard',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Stadium North Endzone',
                        'quantity' => 1,
                        'rated_watts' => 4500,
                        'hours_per_day' => 8,
                        'days_per_month' => 24,
                        'notes' => 'Full-color LED scoreboard display matrix',
                    ],
                    [
                        'name' => 'Grandstand Public Address & Audio System',
                        'category' => 'Other',
                        'location' => 'Control Booth & Grandstand',
                        'quantity' => 1,
                        'rated_watts' => 2200,
                        'hours_per_day' => 6,
                        'days_per_month' => 22,
                        'notes' => 'Arena sound amplification and emergency announcements',
                    ],
                    [
                        'name' => 'Sports Administration Inverter Split AC 2.0HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Sports Development & Admin Offices',
                        'quantity' => 5,
                        'rated_watts' => 1500,
                        'hours_per_day' => 9,
                        'days_per_month' => 22,
                        'notes' => 'Administrative office cooling',
                    ],
                    [
                        'name' => 'Sports Admin Staff PC Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Admin & Ticketing Office',
                        'quantity' => 14,
                        'rated_watts' => 180,
                        'hours_per_day' => 8,
                        'days_per_month' => 22,
                        'notes' => 'Ticketing and sports management terminals',
                    ],
                    [
                        'name' => 'Concession Area Commercial Beverage & Food Coolers',
                        'category' => 'Appliances & Pantry',
                        'location' => 'Concession Stands & Canteen',
                        'quantity' => 5,
                        'rated_watts' => 750,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Continuous refrigeration for drinks and food items',
                    ],
                    [
                        'name' => 'Shower & Restroom Water Booster Pumps 3HP',
                        'category' => 'Pumps & Motors',
                        'location' => 'Locker Rooms Utility Bay',
                        'quantity' => 2,
                        'rated_watts' => 2200,
                        'hours_per_day' => 8,
                        'days_per_month' => 30,
                        'notes' => 'Athlete shower and sanitation water pressurization',
                    ],
                ];
            } elseif (str_contains($facilityName, 'hospital')) {
                // Quezon City General Hospital (~125,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Diagnostic Imaging Suite & Medical Chillers (CT/MRI)',
                        'category' => 'Medical & Specialized',
                        'location' => 'Radiology & Imaging Wing',
                        'quantity' => 2,
                        'rated_watts' => 16000,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Critical precision cooling for superconducting MRI magnets and CT scanners',
                    ],
                    [
                        'name' => 'Operating Room Cleanroom AHU & HEPA HVAC System',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Surgical Suite & Delivery Rooms',
                        'quantity' => 4,
                        'rated_watts' => 8500,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Positive pressure filtered air conditioning for operating theaters',
                    ],
                    [
                        'name' => 'ICU Ventilators & Patient Life-Support Telemetry',
                        'category' => 'Medical & Specialized',
                        'location' => 'Intensive Care Unit (ICU)',
                        'quantity' => 24,
                        'rated_watts' => 350,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Continuous critical care patient life support with emergency UPS',
                    ],
                    [
                        'name' => 'Hospital Central Water Booster & Medical Vacuum Pumps',
                        'category' => 'Pumps & Motors',
                        'location' => 'Basement Utility Plant',
                        'quantity' => 3,
                        'rated_watts' => 7500,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Medical suction lines and hospital building water supply',
                    ],
                    [
                        'name' => 'Inpatient Ward & ER Inverter Split AC 2.5HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Emergency Room & Patient Wards',
                        'quantity' => 28,
                        'rated_watts' => 1850,
                        'hours_per_day' => 18,
                        'days_per_month' => 30,
                        'notes' => 'Comfort cooling for recovery wards and ER intake',
                    ],
                    [
                        'name' => 'Autoclave & Medical Instrument Steam Sterilizers',
                        'category' => 'Medical & Specialized',
                        'location' => 'Central Sterile Services Dept (CSSD)',
                        'quantity' => 3,
                        'rated_watts' => 6000,
                        'hours_per_day' => 8,
                        'days_per_month' => 26,
                        'notes' => 'High pressure surgical instrument steam sterilization',
                    ],
                    [
                        'name' => 'Laboratory Centrifuges & Blood Gas Analyzers',
                        'category' => 'Medical & Specialized',
                        'location' => 'Pathology & Blood Bank Lab',
                        'quantity' => 8,
                        'rated_watts' => 850,
                        'hours_per_day' => 16,
                        'days_per_month' => 30,
                        'notes' => 'Diagnostic clinical laboratory instrumentation',
                    ],
                    [
                        'name' => 'Hospital 24/7 Hallway & Nursing Station LED Fixtures',
                        'category' => 'Lighting',
                        'location' => 'All Floors & Corridors',
                        'quantity' => 160,
                        'rated_watts' => 36,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Continuous clean medical lighting grid',
                    ],
                    [
                        'name' => 'Pharmacy Vaccine & Biological Storage Refrigerators',
                        'category' => 'Appliances & Pantry',
                        'location' => 'Main Hospital Pharmacy',
                        'quantity' => 6,
                        'rated_watts' => 600,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Ultra-stable cold chain vaccine and pharmaceutical refrigeration',
                    ],
                    [
                        'name' => 'Hospital Information System Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Admissions, Billing & Nurse Stations',
                        'quantity' => 45,
                        'rated_watts' => 180,
                        'hours_per_day' => 16,
                        'days_per_month' => 30,
                        'notes' => 'Electronic Medical Record (EMR) encoding stations',
                    ],
                ];
            } elseif (str_contains($facilityName, 'city hall') || str_contains($facilityName, 'main building')) {
                // Quezon City Hall Main Building (~78,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Central VRF High-Capacity Chiller Plant 15HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Rooftop HVAC Mechanical Deck',
                        'quantity' => 6,
                        'rated_watts' => 11000,
                        'hours_per_day' => 10,
                        'days_per_month' => 22,
                        'notes' => 'Multi-zone VRF central air conditioning for Executive & Dept offices',
                    ],
                    [
                        'name' => 'High-Speed Traction Passenger Elevators 20HP',
                        'category' => 'Pumps & Motors',
                        'location' => 'Main Lobby Elevator Bank (Floors 1-14)',
                        'quantity' => 4,
                        'rated_watts' => 15000,
                        'hours_per_day' => 11,
                        'days_per_month' => 26,
                        'notes' => 'Heavy passenger traffic vertical transport with regenerative drives',
                    ],
                    [
                        'name' => 'City MIS Core Server Room & Networking Center',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Data Center Level 4',
                        'quantity' => 1,
                        'rated_watts' => 8500,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Central city database servers, switches, and enterprise UPS backup',
                    ],
                    [
                        'name' => 'Data Center Precision Dual Inverter AC 5HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Data Center Level 4',
                        'quantity' => 2,
                        'rated_watts' => 4200,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Redundant 24/7 precision climate control for server racks',
                    ],
                    [
                        'name' => 'Departmental Desktop PC Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Floors 1 - 14 City Departments',
                        'quantity' => 110,
                        'rated_watts' => 180,
                        'hours_per_day' => 8,
                        'days_per_month' => 22,
                        'notes' => 'Staff and citizen service transaction workstations',
                    ],
                    [
                        'name' => 'High-Output Multi-Function Enterprise Network Copiers',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Records, Assessor & Treasury Depts',
                        'quantity' => 12,
                        'rated_watts' => 450,
                        'hours_per_day' => 7,
                        'days_per_month' => 22,
                        'notes' => 'Heavy-duty department laser printing and scanning centers',
                    ],
                    [
                        'name' => 'Architectural LED Troffer Office Panels 36W',
                        'category' => 'Lighting',
                        'location' => 'Floors 1 - 14 Offices & Corridors',
                        'quantity' => 240,
                        'rated_watts' => 36,
                        'hours_per_day' => 10,
                        'days_per_month' => 22,
                        'notes' => 'High efficiency glare-free office LED panels',
                    ],
                    [
                        'name' => 'Ground Floor Citizens Transaction Hall AC 5HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Ground Floor Public Service Hall',
                        'quantity' => 4,
                        'rated_watts' => 4800,
                        'hours_per_day' => 9,
                        'days_per_month' => 22,
                        'notes' => 'High-traffic public transaction area cooling',
                    ],
                    [
                        'name' => 'High-Rise Domestic Water Booster Pumps 5HP',
                        'category' => 'Pumps & Motors',
                        'location' => 'Basement Water Cistern Room',
                        'quantity' => 2,
                        'rated_watts' => 3750,
                        'hours_per_day' => 8,
                        'days_per_month' => 30,
                        'notes' => 'Multi-stage water pressurization for upper floors',
                    ],
                ];
            } elseif (str_contains($facilityName, 'novaliches')) {
                // Novaliches District Center (~32,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Floor Standing Inverter AC 4.0HP (Public Hall)',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Citizen Transaction Area & Lobby',
                        'quantity' => 4,
                        'rated_watts' => 3600,
                        'hours_per_day' => 9,
                        'days_per_month' => 22,
                        'notes' => 'High duty cycle lobby public area cooling',
                    ],
                    [
                        'name' => 'Inverter Split AC 2.0HP (Offices)',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Treasury, Business Permits & Admin',
                        'quantity' => 8,
                        'rated_watts' => 1500,
                        'hours_per_day' => 9,
                        'days_per_month' => 22,
                        'notes' => 'Departmental staff room cooling',
                    ],
                    [
                        'name' => 'District Government PC Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'All Department Desks',
                        'quantity' => 42,
                        'rated_watts' => 180,
                        'hours_per_day' => 8,
                        'days_per_month' => 22,
                        'notes' => 'Online revenue and permit processing terminals',
                    ],
                    [
                        'name' => 'District Server Rack & Network Switch Hub',
                        'category' => 'IT & Office Equipment',
                        'location' => 'MIS Server Room',
                        'quantity' => 1,
                        'rated_watts' => 1200,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Branch VPN router and local database caching',
                    ],
                    [
                        'name' => 'LED Troffer Ceiling Panels 36W',
                        'category' => 'Lighting',
                        'location' => 'Public Areas & Offices',
                        'quantity' => 85,
                        'rated_watts' => 36,
                        'hours_per_day' => 10,
                        'days_per_month' => 22,
                        'notes' => 'Standard office lighting grid',
                    ],
                    [
                        'name' => 'Building Water Booster Pump 2HP',
                        'category' => 'Pumps & Motors',
                        'location' => 'Ground Utility Pump Room',
                        'quantity' => 1,
                        'rated_watts' => 1500,
                        'hours_per_day' => 6,
                        'days_per_month' => 30,
                        'notes' => 'Building restroom and cleaning water supply',
                    ],
                    [
                        'name' => 'Multi-Function Network Printer/Copiers',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Permits & Records Division',
                        'quantity' => 4,
                        'rated_watts' => 350,
                        'hours_per_day' => 6,
                        'days_per_month' => 22,
                        'notes' => 'Official document print and duplication stations',
                    ],
                ];
            } elseif (str_contains($facilityName, 'library')) {
                // Quezon City Public Library - Main (~18,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Inverter Split AC 2.5HP (Reading Halls)',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Main Reference & Periodicals Hall',
                        'quantity' => 6,
                        'rated_watts' => 2200,
                        'hours_per_day' => 10,
                        'days_per_month' => 26,
                        'notes' => 'Comfort cooling for quiet study and book reading zones',
                    ],
                    [
                        'name' => 'Children Section & Audio-Visual AC 2.0HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Ground Floor Children Wing',
                        'quantity' => 3,
                        'rated_watts' => 1600,
                        'hours_per_day' => 9,
                        'days_per_month' => 26,
                        'notes' => 'Storytelling room and digital media area',
                    ],
                    [
                        'name' => 'E-Library Public Desktop Computer Terminals',
                        'category' => 'IT & Office Equipment',
                        'location' => '2nd Floor Digital Research Room',
                        'quantity' => 35,
                        'rated_watts' => 150,
                        'hours_per_day' => 10,
                        'days_per_month' => 26,
                        'notes' => 'Public Internet research and digital catalog access',
                    ],
                    [
                        'name' => 'Rare Book Archive Precision Dehumidifier Unit',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Filipiniana & Rare Book Vault',
                        'quantity' => 2,
                        'rated_watts' => 1800,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Maintains 50% relative humidity to prevent book mold and paper degradation',
                    ],
                    [
                        'name' => 'Low-Glare Reading Table & Shelf LED Fixtures',
                        'category' => 'Lighting',
                        'location' => 'All Reading Tables & Stacks',
                        'quantity' => 95,
                        'rated_watts' => 24,
                        'hours_per_day' => 10,
                        'days_per_month' => 26,
                        'notes' => 'Targeted book stack and study table illumination',
                    ],
                    [
                        'name' => 'Cataloging & Library Admin Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Technical Services & Administration',
                        'quantity' => 10,
                        'rated_watts' => 180,
                        'hours_per_day' => 9,
                        'days_per_month' => 24,
                        'notes' => 'Book accession and cataloging terminals',
                    ],
                ];
            } elseif (str_contains($facilityName, 'university') || str_contains($facilityName, 'qcu')) {
                // Quezon City University - San Bartolome (~62,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Computer Laboratory PC Fleet (IT & Engineering)',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Tech Building Labs 1-4',
                        'quantity' => 140,
                        'rated_watts' => 180,
                        'hours_per_day' => 10,
                        'days_per_month' => 24,
                        'notes' => 'Hands-on programming and CAD student workstations',
                    ],
                    [
                        'name' => 'Academic Building Split Inverter AC 2.5HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Classrooms & Lecture Halls',
                        'quantity' => 18,
                        'rated_watts' => 2200,
                        'hours_per_day' => 9,
                        'days_per_month' => 24,
                        'notes' => 'Classroom cooling during academic semesters',
                    ],
                    [
                        'name' => 'Campus Auditorium Package AC 10HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Main University Auditorium',
                        'quantity' => 2,
                        'rated_watts' => 9000,
                        'hours_per_day' => 6,
                        'days_per_month' => 16,
                        'notes' => 'Large capacity unit for assemblies and commencement exercises',
                    ],
                    [
                        'name' => 'Campus Perimeter, Walkway & Field Security Floodlights',
                        'category' => 'Lighting',
                        'location' => 'Campus Grounds & Quadrangles',
                        'quantity' => 45,
                        'rated_watts' => 150,
                        'hours_per_day' => 12,
                        'days_per_month' => 30,
                        'notes' => 'High bay security floodlights for evening student safety',
                    ],
                    [
                        'name' => 'Science & Electronics Laboratory Testing Equipment',
                        'category' => 'Medical & Specialized',
                        'location' => 'Science Wing Labs',
                        'quantity' => 12,
                        'rated_watts' => 850,
                        'hours_per_day' => 6,
                        'days_per_month' => 20,
                        'notes' => 'Oscilloscopes, power supplies, centrifuges, and heating mantles',
                    ],
                    [
                        'name' => 'Faculty & Registrar Office Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Admin Building & Dean Offices',
                        'quantity' => 38,
                        'rated_watts' => 180,
                        'hours_per_day' => 8,
                        'days_per_month' => 22,
                        'notes' => 'Enrollment, grading, and departmental computers',
                    ],
                    [
                        'name' => 'Campus Water Pumping Station 5HP',
                        'category' => 'Pumps & Motors',
                        'location' => 'Campus Utility Cistern',
                        'quantity' => 2,
                        'rated_watts' => 3750,
                        'hours_per_day' => 8,
                        'days_per_month' => 30,
                        'notes' => 'Campus-wide elevated water storage distribution',
                    ],
                ];
            } elseif (str_contains($facilityName, 'drrmo')) {
                // QC DRRMO Operations Center (~38,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => '24/7 Command Center Ultra-HD Video Wall Display',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Main Operations Command Hall',
                        'quantity' => 1,
                        'rated_watts' => 5800,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Continuous crisis map and CCTV video wall visualization system',
                    ],
                    [
                        'name' => 'Dedicated Server Room Precision Inverter Cooling 5HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'DRRMO Telecom & Server Vault',
                        'quantity' => 2,
                        'rated_watts' => 4500,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Redundant 24/7 climate control for disaster comms servers',
                    ],
                    [
                        'name' => 'Emergency VHF/UHF Comms Repeaters & Antenna Base',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Comms Tower Control Room',
                        'quantity' => 2,
                        'rated_watts' => 2200,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Uninterrupted two-way emergency radio dispatch repeaters',
                    ],
                    [
                        'name' => '911 Emergency Dispatch Operator Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Call Center Dispatch Floor',
                        'quantity' => 22,
                        'rated_watts' => 220,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Dual-monitor dispatch and computer-aided dispatch (CAD) desks',
                    ],
                    [
                        'name' => 'Command Center Hall High-Efficiency Inverter AC 3HP',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Command Floor & Briefing Room',
                        'quantity' => 3,
                        'rated_watts' => 2800,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Continuous air conditioning for 24/7 duty staff',
                    ],
                    [
                        'name' => 'Operations Center 24/7 Low-Glare LED Lighting',
                        'category' => 'Lighting',
                        'location' => 'Command Floor & Dispatch Rooms',
                        'quantity' => 50,
                        'rated_watts' => 36,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Non-flicker commercial lighting with battery backup',
                    ],
                    [
                        'name' => 'Emergency Weather Radar & Telemetry Receiver Station',
                        'category' => 'Medical & Specialized',
                        'location' => 'Weather Forecasting Unit',
                        'quantity' => 1,
                        'rated_watts' => 1500,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Rainfall telemetry, river flood sensor receiver, and weather feeds',
                    ],
                ];
            } elseif (str_contains($facilityName, 'health') || str_contains($facilityName, 'health department')) {
                // QC Health Department Central Office (~24,000 kWh baseline)
                $sampleLoads = [
                    [
                        'name' => 'Cold Chain Vaccine Refrigerators & Deep Freezers',
                        'category' => 'Appliances & Pantry',
                        'location' => 'Cold Chain Storage Facility',
                        'quantity' => 5,
                        'rated_watts' => 750,
                        'hours_per_day' => 24,
                        'days_per_month' => 30,
                        'notes' => 'Continuous 2-8°C vaccine and biological drug refrigeration',
                    ],
                    [
                        'name' => 'Inverter Split AC 2.0HP (Offices & Clinics)',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Medical Consultation & Admin Rooms',
                        'quantity' => 8,
                        'rated_watts' => 1600,
                        'hours_per_day' => 9,
                        'days_per_month' => 22,
                        'notes' => 'Doctor clinics and health surveillance offices',
                    ],
                    [
                        'name' => 'Health Epidemiology & Surveillance Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Epidemiology & Records Office',
                        'quantity' => 30,
                        'rated_watts' => 180,
                        'hours_per_day' => 8.5,
                        'days_per_month' => 22,
                        'notes' => 'Health records encoding and case tracker terminals',
                    ],
                    [
                        'name' => 'Diagnostic Clinical Laboratory Analyzers & Incubators',
                        'category' => 'Medical & Specialized',
                        'location' => 'Central Health Laboratory',
                        'quantity' => 4,
                        'rated_watts' => 900,
                        'hours_per_day' => 8,
                        'days_per_month' => 22,
                        'notes' => 'Bacteriology and clinical chemistry equipment',
                    ],
                    [
                        'name' => 'Office & Clinic LED Troffer Ceiling Panels 36W',
                        'category' => 'Lighting',
                        'location' => 'Consultation Rooms & Hallways',
                        'quantity' => 70,
                        'rated_watts' => 36,
                        'hours_per_day' => 10,
                        'days_per_month' => 22,
                        'notes' => 'Standard clinical lighting fixtures',
                    ],
                    [
                        'name' => 'Hot & Cold Water Dispensers',
                        'category' => 'Appliances & Pantry',
                        'location' => 'Staff Pantries & Waiting Areas',
                        'quantity' => 4,
                        'rated_watts' => 500,
                        'hours_per_day' => 10,
                        'days_per_month' => 22,
                        'notes' => 'Drinking water stations for patients and staff',
                    ],
                ];
            } else {
                // Standard Municipal / Government Office fallback
                $sampleLoads = [
                    [
                        'name' => 'Inverter Split AC 2.0HP (Admin & Public Desks)',
                        'category' => 'HVAC / Cooling',
                        'location' => 'Main Office Floor',
                        'quantity' => 4,
                        'rated_watts' => 1600,
                        'hours_per_day' => 9,
                        'days_per_month' => 22,
                        'notes' => 'General office comfort cooling',
                    ],
                    [
                        'name' => 'Office Desktop PC Workstations',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Staff Desks',
                        'quantity' => 18,
                        'rated_watts' => 180,
                        'hours_per_day' => 8,
                        'days_per_month' => 22,
                        'notes' => 'Administrative office computers',
                    ],
                    [
                        'name' => 'Department Network Copier & Laser Printer',
                        'category' => 'IT & Office Equipment',
                        'location' => 'Central Records Area',
                        'quantity' => 2,
                        'rated_watts' => 400,
                        'hours_per_day' => 6,
                        'days_per_month' => 22,
                        'notes' => 'Document printing and scanning',
                    ],
                    [
                        'name' => 'LED Ceiling Panels 36W',
                        'category' => 'Lighting',
                        'location' => 'Hallways & Office Rooms',
                        'quantity' => 40,
                        'rated_watts' => 36,
                        'hours_per_day' => 10,
                        'days_per_month' => 22,
                        'notes' => 'Office lighting panels',
                    ],
                    [
                        'name' => 'Water Booster Pump 1.5HP',
                        'category' => 'Pumps & Motors',
                        'location' => 'Utility Tank',
                        'quantity' => 1,
                        'rated_watts' => 1100,
                        'hours_per_day' => 4,
                        'days_per_month' => 30,
                        'notes' => 'Sanitation water pumping',
                    ],
                ];
            }

            foreach ($sampleLoads as $load) {
                SubmeterEquipment::create([
                    'facility_id' => $facility->id,
                    'facility_meter_id' => $mainMeterId,
                    'meter_scope' => 'main',
                    'equipment_name' => $load['name'],
                    'category' => $load['category'],
                    'location' => $load['location'],
                    'quantity' => $load['quantity'],
                    'rated_watts' => $load['rated_watts'],
                    'operating_hours_per_day' => $load['hours_per_day'],
                    'operating_days_per_month' => $load['days_per_month'],
                    'notes' => $load['notes'],
                ]);
            }
        }
    }
}
