<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>COA Energy Report PDF</title>
    <style>
        body {
            font-family: 'Inter', 'Segoe UI', Arial, sans-serif;
            font-size: 14px;
            color: #1f2937;
            margin: 40px;
            background: #ffffff;
        }

        h2 {
            font-size: 1.6rem;
            font-weight: 600;
            margin: 0 0 4px 0;
            color: #111827;
        }

        .period {
            font-size: 0.95rem;
            color: #4b5563;
            margin-bottom: 24px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 12px;
        }

        th {
            text-align: left;
            font-weight: 600;
            font-size: 0.85rem;
            color: #374151;
            padding: 10px 8px;
            border-bottom: 2px solid #e5e7eb;
            background: #f9fafb;
            text-transform: uppercase;
            letter-spacing: 0.04em;
        }

        td {
            padding: 9px 8px;
            border-bottom: 1px solid #e5e7eb;
            font-size: 0.9rem;
        }

        tr:last-child td {
            border-bottom: none;
        }

        .total-row td {
            font-weight: 600;
            background: #f3f4f6;
            border-top: 2px solid #9ca3af;
        }

        .footer {
            margin-top: 32px;
            font-size: 0.85rem;
            color: #6b7280;
            text-align: left;
        }
    </style>
</head>
<body>

    <h2>COA Energy Report</h2>
    <div class="period">
        Reporting Period: <strong><?php echo e(request('from_date')); ?> – <?php echo e(request('to_date')); ?></strong>
    </div>

    <table>
        <thead>
            <tr>
                <?php $__currentLoopData = $columns ?? ['facility','month','actual_kwh','baseline_kwh','variance','trend']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $col): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <th><?php echo e(ucwords(str_replace('_',' ', $col))); ?></th>
                <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
            </tr>
        </thead>
        <tbody>
            <?php $__currentLoopData = array_reverse($energyData ?? []); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $row): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                <tr>
                    <?php $__currentLoopData = $columns ?? ['facility','month','actual_kwh','baseline_kwh','variance','trend']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $col): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                        <td><?php echo e($row[$col] ?? ''); ?></td>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </tr>
            <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>

            <tr class="total-row">
                <td colspan="<?php echo e((isset($columns) ? count($columns) : 6) - 1); ?>">
                    Total Energy Consumption
                </td>
                <td><?php echo e($totalUsage ?? 0); ?> kWh</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        Generated by LGU Energy Efficiency System<br>
        <?php echo e(date('F j, Y')); ?>

    </div>

</body>
</html>
<?php /**PATH C:\xampp\htdocs\energy-system\resources\views/admin/reports/energy-pdf.blade.php ENDPATH**/ ?>